=== Zhuye-zy/Database/second stage/05-官方来源/02-IPDPS补充样例/04-法律状态原始附件/legstat_xml_202122/Root/DTDS/legstat-package-v1.0.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!--Generated by Turbo XML 2.4.1.100.-->

<!--*****************************************************************************
PUBLIC "-//EPO//PACKAGE INDEX 1.0//EN" "package-index-v1-0.dtd"
*****************************************************************************

********************************
* REVISION HISTORY
*********************************
* DATE: 17-02-2014
- Initial version

*****************************************************************************
* SECTION I - DTD
*****************************************************************************

Describes the contents of a package or batch-->
<!ELEMENT legstat-package-index (legstat-package-file+)>

<!--The name of the file containing the current xml instance.-->
<!ATTLIST legstat-package-index date-produced CDATA  #IMPLIED>

<!ATTLIST legstat-package-index dtd-version   CDATA  #IMPLIED>

<!ATTLIST legstat-package-index file          CDATA  #IMPLIED>

<!ATTLIST legstat-package-index id            ID     #IMPLIED>

<!ATTLIST legstat-package-index produced-by   CDATA  #IMPLIED>

<!ATTLIST legstat-package-index volume-id     CDATA  #IMPLIED>

<!--Describes the contents and location of each file within a package.-->
<!ELEMENT legstat-package-file (filename , file-location , doc-id? , subdocs? , imginfo? , legstat-doc-range+)>

<!ATTLIST legstat-package-file  id     ID     #IMPLIED
                                format  (xml | 
                                         tif | 
                                         pdf | 
                                         txt | 
                                         other | 
                                         zip | 
                                         nrm )  #IMPLIED
                                size   CDATA  #IMPLIED >
<!--The name of the physical file.-->
<!ELEMENT filename (#PCDATA)>

<!ATTLIST filename  id ID  #IMPLIED >
<!--The location (url or path) of the file.-->
<!ELEMENT file-location (#PCDATA)>

<!ATTLIST file-location  relative   (true | false )  #IMPLIED >
<!ELEMENT legstat-doc-range (legstat-first-doc-in-range , legstat-last-doc-in-range)>

<!ATTLIST legstat-doc-range  country CDATA  #IMPLIED >
<!ELEMENT legstat-first-doc-in-range (country , doc-number , kind , date)>

<!ELEMENT legstat-last-doc-in-range (country , doc-number , kind , date)>

<!--Document identification refers to patents (and patent applications) only.
See WIPO ST.14
-->
<!ELEMENT doc-id (country , doc-number , kind? , republication-code? , name? , date?)>

<!ATTLIST doc-id  lang     CDATA  #IMPLIED
                    doc-type  (A | P )  #IMPLIED >
<!--Country: use ST.3 country code; e.g. DE, FR, GB, NL, etc.
Also includes EP, WO. Always in upper case. Also can use "stateless"
-->
<!ELEMENT country (#PCDATA)>

<!--The number of the referenced patent (or application) document
-->
<!ELEMENT doc-number (#PCDATA)>

<!--Document kind code; e.g., A1
(INID 13, ST.32:B130)
-->
<!ELEMENT kind (#PCDATA)>

<!--WIPO ST 50 Republication code: NW (for new publications), W1, W2, Z1, Z2, etc...-->
<!ELEMENT republication-code (#PCDATA)>

<!--Name:
If no distinction or detail can be given.
Also to be used for: personal (natural person) and corporate (legal entity) names
-->
<!ELEMENT name (#PCDATA)>

<!ATTLIST name  name-type  (legal | natural )  #IMPLIED >
<!--Date: components of a date. Format: YYYYMMDD
-->
<!ELEMENT date (#PCDATA)>

<!ELEMENT subdocs (subdoc+)>

<!ELEMENT subdoc (#PCDATA)>

<!ATTLIST subdoc  subdoc-code CDATA  #IMPLIED
                    lang        CDATA  #IMPLIED
                    id          ID     #IMPLIED >
<!--For image files, specify also the height, width, etc... in mm of the image.-->
<!ELEMENT imginfo EMPTY>

<!--frame: WIPO ST 33 frame number
page: page number
he: height in mm, for image files
wi: width in mm, for image files-->
<!ATTLIST imginfo he    CDATA  #IMPLIED>

<!ATTLIST imginfo wi    CDATA  #IMPLIED>

<!ATTLIST imginfo page  CDATA  #IMPLIED>

<!ATTLIST imginfo frame CDATA  #IMPLIED>

=== Zhuye-zy/Database/second stage/05-官方来源/02-IPDPS补充样例/04-法律状态原始附件/legstat_xml_202122/Root/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE legstat-package-index PUBLIC "-//EPO//PACKAGE INDEX 1.0//EN" "legstat-package-v1.0.dtd">
<legstat-package-index date-produced="20210529" dtd-version="legstat-package-v1.0.dtd" file="index.xml" produced-by="EP" volume-id="EPLSEEP2021052922001001">
    <legstat-package-file format="ip" size="100729008">
        <filename>LEGSTAT-202122-EP-AppDateFrom19830610-0001.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>83901820</doc-number>
                <kind>A</kind>
                <date>19830610</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>05794659</doc-number>
                <kind>A</kind>
                <date>20050929</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100646812">
        <filename>LEGSTAT-202122-EP-AppDateFrom20050929-0002.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>05804004</doc-number>
                <kind>A</kind>
                <date>20050929</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>09706670</doc-number>
                <kind>A</kind>
                <date>20090130</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100602388">
        <filename>LEGSTAT-202122-EP-AppDateFrom20090130-0003.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>18194365</doc-number>
                <kind>A</kind>
                <date>20090130</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>10801622</doc-number>
                <kind>A</kind>
                <date>20101202</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100625670">
        <filename>LEGSTAT-202122-EP-AppDateFrom20101202-0004.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>10807455</doc-number>
                <kind>A</kind>
                <date>20101202</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>12759952</doc-number>
                <kind>A</kind>
                <date>20120322</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100650419">
        <filename>LEGSTAT-202122-EP-AppDateFrom20120322-0005.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>12761196</doc-number>
                <kind>A</kind>
                <date>20120322</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>13791704</doc-number>
                <kind>A</kind>
                <date>20130408</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100641306">
        <filename>LEGSTAT-202122-EP-AppDateFrom20130408-0006.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>13882029</doc-number>
                <kind>A</kind>
                <date>20130408</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>14742808</doc-number>
                <kind>A</kind>
                <date>20140122</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100658908">
        <filename>LEGSTAT-202122-EP-AppDateFrom20140122-0007.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>14742819</doc-number>
                <kind>A</kind>
                <date>20140122</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>14903665</doc-number>
                <kind>A</kind>
                <date>20141008</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100664344">
        <filename>LEGSTAT-202122-EP-AppDateFrom20141008-0008.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>19157773</doc-number>
                <kind>A</kind>
                <date>20141008</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>15168842</doc-number>
                <kind>A</kind>
                <date>20150522</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100667130">
        <filename>LEGSTAT-202122-EP-AppDateFrom20150522-0009.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>15168956</doc-number>
                <kind>A</kind>
                <date>20150522</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>15863056</doc-number>
                <kind>A</kind>
                <date>20151127</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100745409">
        <filename>LEGSTAT-202122-EP-AppDateFrom20151127-0010.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>15863232</doc-number>
                <kind>A</kind>
                <date>20151127</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>16741775</doc-number>
                <kind>A</kind>
                <date>20160713</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100650705">
        <filename>LEGSTAT-202122-EP-AppDateFrom20160713-0011.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
                <doc-number>16742203</doc-number>
                <kind>A</kind>
                <date>20160713</date>
            </legstat-first-doc-in-range>
            <legstat-last-doc-in-range>
                <country>EP</country>
                <doc-number>16784692</doc-number>
                <kind>A</kind>
                <date>20161010</date>
            </legstat-last-doc-in-range>
        </legstat-doc-range>
    </legstat-package-file>
    <legstat-package-file format="ip" size="100753659">
        <filename>LEGSTAT-202122-EP-AppDateFrom20161010-0012.xml</filename>
        <file-location relative="true">/shared/appdata/lss_exchange-platform/tmp/frontfile/legstat_xml_202122/Root/DOC</file-location>
        <legstat-doc-range country="EP">
            <legstat-first-doc-in-range>
                <country>EP</country>
